from django.contrib import admin
from asesorias import models

admin.site.register(models.Centro)
admin.site.register(models.AdministradorCentro)
admin.site.register(models.CentroAdministradorCentro)
admin.site.register(models.Titulacion)
admin.site.register(models.Asignatura)
admin.site.register(models.AsignaturaCursoAcademico)
admin.site.register(models.Departamento)
admin.site.register(models.Asesor)
admin.site.register(models.AsesorCursoAcademico)
admin.site.register(models.PlantillaEntrevistaAsesor)
admin.site.register(models.PreguntaAsesor)
admin.site.register(models.Alumno)
admin.site.register(models.AlumnoCursoAcademico)
admin.site.register(models.Matricula)
admin.site.register(models.CalificacionConvocatoria)
admin.site.register(models.PlantillaEntrevistaOficial)
admin.site.register(models.PreguntaOficial)
admin.site.register(models.Reunion)
admin.site.register(models.ReunionPreguntaAsesor)
admin.site.register(models.ReunionPreguntaOficial)
